apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtvalidate.fullname" . }}-config
  labels:
    {{- include "virtvalidate.labels" . | nindent 4 }}
data:
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  MTV_NAMESPACE: {{ .Values.config.mtvNamespace | quote }}
  MTV_SOURCE_PROVIDER: {{ .Values.config.mtvSourceProvider | quote }}
  MTV_DESTINATION_PROVIDER: {{ .Values.config.mtvDestinationProvider | quote }}
  MTV_DEFAULT_TARGET_NAMESPACE: {{ .Values.config.mtvDefaultTargetNamespace | quote }}
  FIPS_MODE: {{ .Values.security.fipsMode | quote }}
  SSH_KEY_ALGORITHM: {{ .Values.security.sshKeyAlgorithm | quote }}
