apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtvalidate-ssh-keys
  labels:
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
