apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: virtvalidate-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: virtvalidate
      app.kubernetes.io/component: backend
