apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtvalidate-ollama-models
  labels:
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
