"""planning strategy and plan revisions

Revision ID: f80aef3398ae
Revises: 7ac5c2122588
Create Date: 2026-05-04 14:08:06.324236

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f80aef3398ae'
down_revision: str | Sequence[str] | None = '7ac5c2122588'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_grouping', sa.Enum('application', 'vcenter_folder', 'application_owner', 'environment', 'business_unit', 'data_classification', 'llm_decides', name='primary_grouping'), server_default='application', nullable=False),
    sa.Column('wave_size_target', sa.Enum('small_5_10', 'medium_10_20', 'large_20_50', 'custom', name='wave_size_target'), server_default='medium_10_20', nullable=False),
    sa.Column('wave_size_custom', sa.Integer(), nullable=True),
    sa.Column('risk_approach', sa.Enum('low_first', 'high_first', 'mixed', name='risk_approach'), server_default='mixed', nullable=False),
    sa.Column('production_handling', sa.Enum('mixed', 'non_prod_first', 'prod_dedicated_waves', name='production_handling'), server_default='non_prod_first', nullable=False),
    sa.Column('application_atomicity', sa.Enum('all_together', 'can_split', 'per_app_choice', name='application_atomicity'), server_default='all_together', nullable=False),
    sa.Column('freeform_constraints', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by_actor', sa.String(length=255), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('migration_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), server_default='Untitled plan', nullable=False))
        batch_op.add_column(sa.Column('strategy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('generation_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generation_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plan_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rationale', sa.Text(), nullable=True))
        # Server-side default = empty JSON array so existing legacy
        # migration_plans rows survive the NOT NULL add. Autogenerate
        # doesn't infer this from the model's Python-side `default=list`.
        batch_op.add_column(sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('next_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('supersedes_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revision_number', sa.Integer(), server_default='1', nullable=False))
        # Named so batch-mode downgrade on SQLite can drop them by name.
        batch_op.create_foreign_key('fk_migration_plans_strategy_id', 'planning_strategies', ['strategy_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_migration_plans_supersedes_plan_id', 'migration_plans', ['supersedes_plan_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('migration_plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_migration_plans_supersedes_plan_id', type_='foreignkey')
        batch_op.drop_constraint('fk_migration_plans_strategy_id', type_='foreignkey')
        batch_op.drop_column('revision_number')
        batch_op.drop_column('supersedes_plan_id')
        batch_op.drop_column('next_actions')
        batch_op.drop_column('warnings')
        batch_op.drop_column('rationale')
        batch_op.drop_column('plan_summary')
        batch_op.drop_column('generation_response')
        batch_op.drop_column('generation_prompt')
        batch_op.drop_column('strategy_id')
        batch_op.drop_column('name')

    op.drop_table('planning_strategies')
    # ### end Alembic commands ###
