"""ocp targets and resource mappings

Revision ID: 8f96c847dcaf
Revises: f80aef3398ae
Create Date: 2026-05-05 21:40:59.855145

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8f96c847dcaf'
down_revision: str | Sequence[str] | None = 'f80aef3398ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocp_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('api_endpoint', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('classification_level', sa.Enum('unclassified', 'cui', 'secret', 'top_secret', name='ocp_target_classification_level'), server_default='unclassified', nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', name='ocp_target_status'), server_default='inactive', nullable=False),
    sa.Column('auth_type', sa.Enum('token', 'service_account', 'kubeconfig', name='ocp_target_auth_type'), server_default='token', nullable=False),
    sa.Column('auth_credential_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('storage_classes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('network_attachments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('namespaces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cluster_capacity', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('mtv_namespace', sa.String(length=253), nullable=True),
    sa.Column('ocp_version', sa.String(length=32), nullable=True),
    sa.Column('kubernetes_version', sa.String(length=32), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('ocp_targets', schema=None) as batch_op:
        batch_op.create_index('ix_ocp_targets_classification', ['classification_level'], unique=False)
        batch_op.create_index('ix_ocp_targets_status', ['status'], unique=False)

    op.create_table('resource_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vcenter_source_id', sa.Integer(), nullable=False),
    sa.Column('ocp_target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('complete', 'incomplete', 'needs_review', name='resource_mapping_status'), server_default='incomplete', nullable=False),
    sa.Column('network_mappings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('storage_mappings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('namespace_mappings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ocp_target_id'], ['ocp_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vcenter_source_id'], ['vcenter_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vcenter_source_id', 'ocp_target_id', 'name', name='uq_mapping_source_target_name')
    )
    with op.batch_alter_table('resource_mappings', schema=None) as batch_op:
        batch_op.create_index('ix_mappings_source_target', ['vcenter_source_id', 'ocp_target_id'], unique=False)
        batch_op.create_index('ix_mappings_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_mappings', schema=None) as batch_op:
        batch_op.drop_index('ix_mappings_status')
        batch_op.drop_index('ix_mappings_source_target')

    op.drop_table('resource_mappings')
    with op.batch_alter_table('ocp_targets', schema=None) as batch_op:
        batch_op.drop_index('ix_ocp_targets_status')
        batch_op.drop_index('ix_ocp_targets_classification')

    op.drop_table('ocp_targets')
    # ### end Alembic commands ###
