"""validation scaling tables

Revision ID: 4963cfaf09eb
Revises: fcb533072d50
Create Date: 2026-05-11 19:27:57.154189

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4963cfaf09eb"
down_revision: str | Sequence[str] | None = "fcb533072d50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_llm_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("os_family", sa.String(length=32), nullable=False),
        sa.Column(
            "verdict",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("hit_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_vm_id", sa.Integer(), nullable=True),
        sa.Column("source_model", sa.String(length=128), nullable=True),
        sa.Column("diff_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    with op.batch_alter_table("validation_llm_cache", schema=None) as batch_op:
        batch_op.create_index("ix_validation_llm_cache_expires", ["expires_at"], unique=False)
        batch_op.create_index("ix_validation_llm_cache_key", ["cache_key"], unique=False)

    op.create_table(
        "validation_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("cron_expression", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("enabled", "paused", "disabled", name="validation_schedule_status"),
            server_default="enabled",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_task_id", sa.String(length=64), nullable=True),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("runtime_paused", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_by_actor", sa.String(length=255), server_default="user", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("validation_schedules", schema=None) as batch_op:
        batch_op.create_index("ix_validation_schedules_status", ["status"], unique=False)

    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("backend_type", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("vm_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vm_id"], ["vms.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.create_index("ix_llm_usage_op_time", ["operation", "created_at"], unique=False)
        batch_op.create_index("ix_llm_usage_time", ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_usage_time")
        batch_op.drop_index("ix_llm_usage_op_time")

    op.drop_table("llm_usage")
    with op.batch_alter_table("validation_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_validation_schedules_status")

    op.drop_table("validation_schedules")
    with op.batch_alter_table("validation_llm_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_validation_llm_cache_key")
        batch_op.drop_index("ix_validation_llm_cache_expires")

    op.drop_table("validation_llm_cache")
    # ### end Alembic commands ###
