"""storage design review tables

Revision ID: 7ac5c2122588
Revises: 7c34de23960e
Create Date: 2026-05-04 13:45:46.740890

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7ac5c2122588"
down_revision: str | Sequence[str] | None = "7c34de23960e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_design_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "analyzing", "completed", "failed", name="storage_review_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("customer_notes", sa.Text(), server_default="", nullable=False),
        sa.Column("proposed_yaml", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "analysis_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storage_findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "performance_tier_mismatch",
                "capacity_concern",
                "access_mode_mismatch",
                "replication_loss",
                "snapshot_capability",
                "multipath_policy",
                "positive_confirmation",
                name="storage_finding_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("critical", "high", "medium", "low", "info", name="storage_finding_severity"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("high", "medium", "low", name="storage_finding_confidence"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "triage",
            sa.Enum("open", "accepted", "dismissed", name="storage_finding_triage"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("source_evidence", sa.Text(), server_default="", nullable=False),
        sa.Column("proposed_evidence", sa.Text(), server_default="", nullable=False),
        sa.Column("recommendation", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_id"], ["storage_design_reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("storage_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_storage_findings_review_id"), ["review_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_findings_review_id"))

    op.drop_table("storage_findings")
    op.drop_table("storage_design_reviews")
    # ### end Alembic commands ###
