"""baseline schema for v0.1

Revision ID: 7c34de23960e
Revises: 
Create Date: 2026-05-02 19:23:37.846476

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7c34de23960e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ollama_model', sa.String(length=128), nullable=False),
    sa.Column('schedule_preset', sa.Enum('twice_daily', 'once_daily', 'hourly', name='schedule_preset'), nullable=False),
    sa.Column('ssh_host_key_policy', sa.Enum('auto_accept', 'strict', name='ssh_host_key_policy'), server_default='auto_accept', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('migration_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('waves', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('source_vcenter_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strategy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('network_design_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'analyzing', 'completed', 'failed', name='network_review_status'), server_default='draft', nullable=False),
    sa.Column('customer_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('proposed_yaml', sa.Text(), server_default='', nullable=False),
    sa.Column('analysis_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vcenter_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('classification_level', sa.Enum('unclassified', 'cui', 'secret', 'top_secret', name='classification_level'), server_default='unclassified', nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'archived', name='vcenter_status'), server_default='active', nullable=False),
    sa.Column('default_target_namespace', sa.String(length=253), nullable=True),
    sa.Column('default_target_storage_class', sa.String(length=253), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('vcenter_sources', schema=None) as batch_op:
        batch_op.create_index('ix_vcenter_classification', ['classification_level'], unique=False)
        batch_op.create_index('ix_vcenter_status', ['status'], unique=False)

    op.create_table('network_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('coverage_gap', 'config_mismatch', 'missing_resource', 'positive_confirmation', name='network_finding_category'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='network_finding_severity'), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='network_finding_confidence'), server_default='medium', nullable=False),
    sa.Column('triage', sa.Enum('open', 'accepted', 'dismissed', name='network_finding_triage'), server_default='open', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('source_evidence', sa.Text(), server_default='', nullable=False),
    sa.Column('proposed_evidence', sa.Text(), server_default='', nullable=False),
    sa.Column('recommendation', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['network_design_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_findings_review_id'), ['review_id'], unique=False)

    op.create_table('vm_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_vcenter_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('application', 'environment', 'business_unit', 'other', name='vm_group_kind'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_by_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_vcenter_id'], ['vcenter_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_vcenter_id', 'kind', 'name', name='uq_group_vcenter_kind_name')
    )
    with op.batch_alter_table('vm_groups', schema=None) as batch_op:
        batch_op.create_index('ix_groups_vcenter_kind', ['source_vcenter_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_vm_groups_source_vcenter_id'), ['source_vcenter_id'], unique=False)

    op.create_table('vms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_hostname', sa.String(length=255), nullable=False),
    sa.Column('target_hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('os_family', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('ssh_user', sa.String(length=64), nullable=True),
    sa.Column('ssh_port', sa.Integer(), server_default='22', nullable=False),
    sa.Column('current_platform', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'baseline_captured', 'migrated', 'validated', 'failed', name='vm_status'), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('vsphere_networks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vsphere_datastores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_namespace', sa.String(length=253), nullable=True),
    sa.Column('target_storage_class', sa.String(length=253), nullable=True),
    sa.Column('target_network_attachment', sa.String(length=253), nullable=True),
    sa.Column('source_vcenter_id', sa.Integer(), nullable=True),
    sa.Column('application_hint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_vcenter_id'], ['vcenter_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.create_index('ix_vms_app_env', ['application_hint', 'environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_vms_name'), ['name'], unique=True)
        batch_op.create_index('ix_vms_source_vcenter_status', ['source_vcenter_id', 'status'], unique=False)
        batch_op.create_index('ix_vms_target_namespace', ['target_namespace'], unique=False)

    op.create_table('baseline_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_number', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_snapshots_vm_id'), ['vm_id'], unique=False)
        batch_op.create_index('ix_snapshots_vm_collected_at', ['vm_id', 'collected_at'], unique=False)
        batch_op.create_index('ix_snapshots_vm_snapshot_number', ['vm_id', 'snapshot_number'], unique=True)

    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'warn', 'failed', name='validation_status'), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('remediation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_vm_id'), ['vm_id'], unique=False)
        batch_op.create_index('ix_validation_vm_validated_at', ['vm_id', 'validated_at'], unique=False)

    op.create_table('vm_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('rationale', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['vm_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'vm_id', name='uq_member_group_vm')
    )
    with op.batch_alter_table('vm_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vm_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vm_group_members_vm_id'), ['vm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vm_group_members_vm_id'))
        batch_op.drop_index(batch_op.f('ix_vm_group_members_group_id'))

    op.drop_table('vm_group_members')
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_validation_vm_validated_at')
        batch_op.drop_index(batch_op.f('ix_validation_results_vm_id'))

    op.drop_table('validation_results')
    with op.batch_alter_table('baseline_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_vm_snapshot_number')
        batch_op.drop_index('ix_snapshots_vm_collected_at')
        batch_op.drop_index(batch_op.f('ix_baseline_snapshots_vm_id'))

    op.drop_table('baseline_snapshots')
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.drop_index('ix_vms_target_namespace')
        batch_op.drop_index('ix_vms_source_vcenter_status')
        batch_op.drop_index(batch_op.f('ix_vms_name'))
        batch_op.drop_index('ix_vms_app_env')

    op.drop_table('vms')
    with op.batch_alter_table('vm_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vm_groups_source_vcenter_id'))
        batch_op.drop_index('ix_groups_vcenter_kind')

    op.drop_table('vm_groups')
    with op.batch_alter_table('network_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_findings_review_id'))

    op.drop_table('network_findings')
    with op.batch_alter_table('vcenter_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_vcenter_status')
        batch_op.drop_index('ix_vcenter_classification')

    op.drop_table('vcenter_sources')
    op.drop_table('network_design_reviews')
    op.drop_table('migration_programs')
    op.drop_table('migration_plans')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
