"""vm rvtools lifecycle columns

Revision ID: caa9eb0a9c2e
Revises: bdcc6835d70a
Create Date: 2026-05-06 00:52:43.991821

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'caa9eb0a9c2e'
down_revision: str | Sequence[str] | None = 'bdcc6835d70a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missing_from_last_upload', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_seen_in_upload_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.drop_column('last_seen_in_upload_at')
        batch_op.drop_column('missing_from_last_upload')

    # ### end Alembic commands ###
