"""plan_chunks table

Revision ID: fcb533072d50
Revises: caa9eb0a9c2e
Create Date: 2026-05-06 03:06:49.384914

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'fcb533072d50'
down_revision: str | Sequence[str] | None = 'caa9eb0a9c2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('reason_for_chunk', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sub_key', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vm_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sequence_dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('chunk_rationale', sa.Text(), nullable=True),
    sa.Column('chunk_risk_level', sa.String(length=16), nullable=True),
    sa.Column('wave_numbers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_plan_chunks_plan_id', ['plan_id'], unique=False)
        batch_op.create_index('ix_plan_chunks_plan_seq', ['plan_id', 'sequence_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_chunks_plan_seq')
        batch_op.drop_index('ix_plan_chunks_plan_id')

    op.drop_table('plan_chunks')
    # ### end Alembic commands ###
